Added footer CSS for desktop
iitsldev/iit_web_app pull request #10
Opened 2021-11-26 13:47 UTC by NadeekaJK

2021-11-26 15:21 UTC, yalacat requested changes
1. There are some responsiveness related issues for all screens except larger screens.
Pls refer the below image.
![image](https://user-images.githubusercontent.com/48783321/143600073-828f385b-28ee-4ec1-9d1b-b661d3d1cfa8.png)

2. In terms of the responsiveness, it was earlier working (80% of the screens) 

3. Also, be careful when changing the CSS class names as it could lead to UI breaks.

2021-11-27 01:06 UTC, NadeekaJK commented
> **Pls do not merge until these are resovled.**
> 
> 1. There are some responsiveness related issues for all screens except larger screens.
>    Pls refer the below image.
>    ![image](https://user-images.githubusercontent.com/48783321/143600073-828f385b-28ee-4ec1-9d1b-b661d3d1cfa8.png)
> 2. In terms of the responsiveness, it was earlier working (80% of the screens)
> 3. Also, be careful when changing the CSS class names as it could lead to UI breaks.

1. Yes, these changes are only for large screens, as mentioned in the topic of the PR. Changes for mobile and ipad is in progress, and will come as separate PRs. I don't see an issue in merging them as separate PR s, do you?
2. Yes, due to CSS changes introduced this also needs to be addressed separately, and is in progress.
3. Sure, let me know if there's such class names in this change that needs to be altered. So far no issues with class names.

2021-11-27 06:44 UTC, ssomlk approved these changes

2021-11-27 08:32 UTC, yalacat approved these changes

2021-11-27 08:32 UTC, merged