Update styles for common header section
iitsldev/iit_web_app pull request #12
Opened 2021-11-26 14:12 UTC by krrb

2021-11-26 15:06 UTC, ssomlk commented
There seems to be issues. I have already done this Rajiv. Mobile responsiveness is gone. 

![image](https://user-images.githubusercontent.com/30547921/143599901-c0de6fe9-e88b-4094-a995-7731de552af5.png)

![image](https://user-images.githubusercontent.com/30547921/143600078-21a3964e-fe08-4e79-95b3-fc7b12163373.png)

![image](https://user-images.githubusercontent.com/30547921/143600142-243d4b24-4d94-486d-bd81-599c54ca9237.png)

2021-11-26 15:21 UTC, ssomlk requested changes
****** IMPORTANT ***********************

PLEASE DO NOT MERGE TO MASTER

2021-11-27 05:47 UTC, krrb commented
![image](https://user-images.githubusercontent.com/30167597/143669677-4782f3ec-992d-4ecf-a151-c3680d0f309d.png)

![image](https://user-images.githubusercontent.com/30167597/143669688-adb5da33-20dd-44de-834d-b36c6225de5d.png)

![image](https://user-images.githubusercontent.com/30167597/143669693-4c0af4d0-7b42-4175-885e-ccc3d88c9366.png)

![image](https://user-images.githubusercontent.com/30167597/143669700-ecb89a01-f69a-4e58-8ef1-dcf903204cc8.png)

Fixed responsive issues

Changes are done only for MainCommonLayoutSection component

2021-11-27 06:13 UTC, ssomlk approved these changes

2021-11-27 06:13 UTC, merged